repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        name: Seed isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100, --target-version=py37]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^.bumpversion.cfg
      - id: trailing-whitespace
        exclude: ^.bumpversion.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.790"
    hooks:
      - id: mypy
        name: Lint core with mypy
        files: ^dbt_sugar/core/
        entry: mypy dbt_sugar/core
        pass_filenames: false
        args: [--ignore-missing-imports]
  - repo: https://github.com/PyCQA/isort
    rev: "5.6.4"
    hooks:
      - id: isort
        name: Sort import with isort
        args: ["-m3", "-w 100", "--tc"]
        exclude: ^tests/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
        exclude: ^tests/
        additional_dependencies: [flake8-docstrings]
        args: ["--max-line-length=120", "--ignore=D102,D104,D401,D400"]
